[package]
name = "glonax"
version = "0.3.1"
authors = ["Laixer Equipent B.V. <info@laixer.com>"]
edition = "2018"

[dependencies]
serialport = "4.0.1"
serial = "0.4"
nom = "6.2.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
clap = "2.33.3"
gilrs = "^0.8"
log = "0.4.14"
simplelog = "0.10.0"
tokio = { version = "1.7.0", features = ["full"] }
bytes = "1"
pid = "3.0.0"
crc = "2.0.0"
