[package]
name = "glonax"
version = "0.6.2"
authors = ["Laixer Equipment B.V. <info@laixer.com>"]
edition = "2018"
repository = "https://github.com/Laixer/Glonax"
description = """
Heavy machinery controller daemon
"""
categories = ["hardware", "machine", "controller"]
keywords = ["hardware", "machine", "controller"]

[[bin]]
name = "glonaxd"
path = "src/main.rs"

[dependencies]
glonax-core = { version = "1.0.0", path = "../glonax-core" }
glonax-ice = { version = "1.0.6", path = "../glonax-ice" }

serial = "0.4"
clap = "2.33.3"
log = "0.4.14"
simplelog = "0.10.0"
gilrs = "^0.8"
tokio = { version = "1.7", features = ["full"] }
pid = "3.0.0"
sled = "0.34.6"
