[package]
name = "glonax"
version = "0.9.2"
authors = ["Laixer Equipment B.V. <info@laixer.com>"]
edition = "2021"
repository = "https://github.com/Laixer/Glonax"
description = """
Heavy equipment controller daemon
"""
categories = ["hardware", "machine", "controller"]
keywords = ["hardware", "machine", "controller"]

[[bin]]
name = "glonaxd"
path = "src/main.rs"

[dependencies]
glonax-core = { version = "1.0", path = "../glonax-core" }
glonax-ice = { version = "1.0", path = "../glonax-ice" }
glonax-j1939 = { version = "1.0", path = "../glonax-j1939" }
glonax-serial = { version = "1.0", path = "../glonax-serial" }
glonax-gamepad = { version = "1.0", path = "../glonax-gamepad" }

clap = { version = "3.1", features = ["derive"] }
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
simplelog = "0.10.0"
tokio = { version = "1.7", features = ["full"] }
anyhow = "1.0"
async-trait = "0.1.51"
fs2 = "0.4.3"
udev = "0.6.2"
csv = "1.1.6"
uuid = { version = "0.8.2", features = ["v4"] }
ansi_term = "0.12"
