[package]
name = "glonax-ecu"
version = "1.0.0"
authors = ["Laixer Equipment B.V. <info@laixer.com>"]
edition = "2021"
repository = "https://github.com/Laixer/Glonax"

[dependencies]
glonax = { version = "2.1.14", path = "../glonax-runtime" }

log = "0.4"
anyhow = "1.0"
tokio = { version = "1.18", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
simplelog = "0.12"

[[bin]]
name = "glonax-ecud"
path = "src/main.rs"
