[package]
name = "glonax-net"
version = "0.3.1"
authors = ["Laixer Equipent B.V. <info@laixer.com>"]
edition = "2021"

[dependencies]
log = "0.4"
tokio = { version = "1.25", features = ["full"] }
bytes = "1"
