[package]
name = "glonax-net"
version = "0.3.1"
authors = ["Laixer Equipent B.V. <info@laixer.com>"]
edition = "2018"

[dependencies]
log = "0.4.14"
tokio = { version = "1.7.0", features = ["full"] }
bytes = "1"
