[package]
name = "glonax-core"
version = "1.0.0"
authors = ["Laixer Equipment B.V. <info@laixer.com>"]
edition = "2021"

[dependencies]
nalgebra = "0.31"
serde = { version = "1.0", features = ["derive"] }