#!/bin/bash
# Copyright (c) 2021-2024 Laixer B.V.
#
# Debian package post-installation script.

set -e

# Reload the udev rules
if command -v udevadm &> /dev/null; then
  echo -n "Reloading udev rules.."
  udevadm control --reload-rules
  echo "..done"
fi

# Enable a service and restart if it is currently running.
enable_glonax_service() {
  local SERVICE_NAME="$1"

  if systemctl is-active "$SERVICE_NAME" &> /dev/null; then
    echo -n "Restarting $SERVICE_NAME.."
    systemctl restart "$SERVICE_NAME"
    echo "..done"
  fi

  echo -n "Enabling $SERVICE_NAME.."
  systemctl enable "$SERVICE_NAME"
  echo "..done"
}

# Enable the glonax services if systemd is available
if [ -d /run/systemd/system ]; then
  # Reload the systemd daemon to pick up the new service files
  echo -n "Reloading systemd units.."
  systemctl daemon-reload
  echo "..done"

  enable_glonax_service glonax.service
fi
