#!/bin/bash
# Copyright (c) 2021-2024 Laixer B.V.
#
# Debian package post-installation script.

set -e

USERNAME_DAEMON="glonaxd"
USERNAME_INPUT="glonax-input"
GROUPNAME="glonax"

group_add() {
  local GROUPNAME="$1"

  if getent group "$GROUPNAME" &>/dev/null; then
    echo "Group $GROUPNAME already exists. Skipping group creation."
  else
    groupadd "$GROUPNAME" --system
    if [ $? -eq 0 ]; then
      echo "Group $GROUPNAME has been successfully created."
    else
      echo "Failed to create group $GROUPNAME. Please check system logs for more information."
      exit 1
    fi
  fi
}

user_add() {
  local USERNAME="$1"
  local GROUPNAME="$2"

  if id "$USERNAME" &>/dev/null; then
    echo "User $USERNAME already exists. Skipping user creation."
  else
    useradd --system --no-create-home --shell /usr/sbin/nologin --gid "$GROUPNAME" "$USERNAME"
    if [ $? -eq 0 ]; then
      echo "User $USERNAME has been successfully created and added to group $GROUPNAME."
    else
      echo "Failed to create user $USERNAME. Please check system logs for more information."
      exit 1
    fi
  fi
}

# Add the glonax group
group_add "$GROUPNAME"
user_add "$USERNAME_DAEMON" "$GROUPNAME"
user_add "$USERNAME_INPUT" "$GROUPNAME"

# Reload the udev rules
if command -v udevadm &> /dev/null; then
  echo -n "Reloading udev rules.."
  udevadm control --reload-rules
  echo "..done"
fi

# Restart the glonax service
systemd_start_service() {
  local SERVICE_NAME="$1"

  if systemctl is-active "$SERVICE_NAME" &> /dev/null; then
    echo -n "Restarting $SERVICE_NAME.."
    systemctl restart "$SERVICE_NAME"
    echo "..done"
  fi
}

# Enable the glonax services if systemd is available
if [ -d /run/systemd/system ]; then
  # Reload the systemd daemon to pick up the new service files
  echo -n "Reloading systemd units.."
  systemctl daemon-reload
  echo "..done"

  # systemd_start_service glonax.service
fi

exit 0