[package]
name = "glonax-input"
version = "1.0.0"
authors = ["Laixer Equipment B.V. <info@laixer.com>"]
edition = "2021"
repository = "https://github.com/Laixer/Glonax"

[dependencies]
glonax = { version = "2.1.14", path = "../glonax-runtime" }
glonax-gamepad = { version = "1.0", path = "../glonax-gamepad" }

log = "0.4"
anyhow = "1.0"
tokio = { version = "1.25", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
simplelog = "0.12"

[[bin]]
name = "glonax-inputd"
path = "src/main.rs"
