[package]
name = "glonax-input"
version = "1.0.0"
authors = ["Laixer Equipment B.V. <info@laixer.com>"]
edition = "2021"
repository = "https://github.com/Laixer/Glonax"

[dependencies]
glonax = { version = "3.1", path = "../glonax-runtime" }
glonax-gamepad = { version = "1.0", path = "../glonax-gamepad" }

tonic = "0.8"

log = "0.4"
anyhow = "1.0"
tokio = { version = "1.27", features = ["full"] }
clap = { version = "4.1", features = ["derive"] }
simplelog = "0.12"

[[bin]]
name = "glonax-inputd"
path = "src/main.rs"
