name: Rust

on:
  push:
    branches: [ "main", "wip" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PostgreSQL development tools
      run: sudo apt install debhelper fakeroot

    - name: Show environment
      run: rustup show

    - name: Run tests
      run: cargo test --release --all-features

    # - name: Build deb
    #   run: ./scripts/package.sh

    # - name: Install deb
    #   run: sudo dpkg -i ./target/glonax*.deb

    # - name: Test install
    #   run: |
    #     glonax-csim -V
    #     glonax-ecud -V
    #     glonax-gnssd -V
    #     glonax-input -V
    #     glonax-netctl -V
    #     glonax-agent -V
    #     glonax-proxyd -V

    # - name: Publish artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: glonax-${{ github.ref_name }}.deb
    #     path: ./target/**.deb
