name: Rust

on:
  push:
    branches: [ "main", "wip" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --release

    - name: Build deb
      run: ./scripts/package.sh

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: glonax.deb
        path: ./target/**.deb
