name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install libudev-dev

    - name: Build
      run: cargo build --release

    - name: Build deb
      run: ./scripts/package.sh

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./target/**.deb

#    - name: Run tests
#      run: cargo test --release
